# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5aaa8268d95f709f0a6398fdde6f1b2d4df76d32078e09424657cbdd434152c29cec184b621e1986f93178fb53afdc41937311cc17d94505867d2b8e204cce7

test:
  secret_key_base: 3bbe4f357e631f0d796d48a055b6ed3e427a9059eb26243387dc3b730583d4748ee8ce050653a883fb5e2e7744620789dadbf766bdc449dfc3f33fc16fe9ce80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
